import streamlit as st
import pandas as pd
import json
import sys

# ==========================================
# 1. DATA SETUP
# ==========================================

@st.cache_data
def load_data():
    """Loads and preprocesses all necessary data from external files."""
    
    # A. Load Courses
    try:
        df_courses = pd.read_csv('courses.csv')
    except FileNotFoundError:
        st.error("Error: 'courses.csv' not found. Ensure it's in the same directory.")
        st.stop()
        
    # B. Load Students (Updated to read from large dataset)
    try:
        df_students = pd.read_csv('student_data_large.csv')
    except FileNotFoundError:
        st.error("Error: 'student_data_large.csv' not found. Please ensure the file exists.")
        st.stop()
    
    # C. Load Schedule (Updated to read the JSON generated by new_test.py)
    # Note: new_test.py outputs to 'timetable_output.json'
    try:
        with open('new_timetable_output.json', 'r') as f:
            schedule_data = json.load(f)
        df_schedule = pd.DataFrame(schedule_data)
    except FileNotFoundError:
        st.error("Error: 'timetable_output.json' not found. Please run new_test.py first.")
        st.stop()
    except Exception as e:
        st.error(f"Error loading schedule data: {e}")
        st.stop()
        
    return df_courses, df_students, df_schedule

# ==========================================
# 2. APP LOGIC
# ==========================================

def get_student_schedule(student_id, df_students, df_schedule, df_courses):
    """Filters the master schedule for a specific student ID."""
    
    # 1. Get the list of Course IDs (CIDs) the student is enrolled in
    enrolled_cids = df_students[df_students['student_id'] == student_id]['course_id'].tolist()
    
    if not enrolled_cids:
        return None, None
    
    # Get student name
    student_name_series = df_students[df_students['student_id'] == student_id]['student_name']
    if student_name_series.empty:
        return None, None
    student_name = student_name_series.iloc[0]

    # 2. Filter the master schedule by the enrolled CIDs
    if df_schedule.empty:
        return student_name, pd.DataFrame()
        
    student_sched = df_schedule[df_schedule['Course'].isin(enrolled_cids)].copy()
    
    # 3. Format for display (Pivot Table)
    day_order = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri']
    
    if student_sched.empty:
        return student_name, pd.DataFrame()

    # Create a nice display entry with Title (Room)
    # Ensure Title exists, fallback to Course ID if missing
    student_sched['Display_Entry'] = student_sched.apply(
        lambda row: f"{str(row['Title']).split('-')[0]} ({row['Room']})", axis=1
    )
    
    # Pivot the data to create the weekly grid
    pivot_table = student_sched.pivot_table(
        index='Slot', 
        columns='Day', 
        values='Display_Entry', 
        aggfunc=lambda x: '<br>'.join(x) # Use <br> for multiple classes in one slot
    ).fillna('')
    
    # Reorder the columns to ensure Mon-Fri order
    existing_days = [d for d in day_order if d in pivot_table.columns]
    pivot_table = pivot_table.reindex(columns=existing_days)
    
    return student_name, pivot_table

# ==========================================
# 3. STREAMLIT UI
# ==========================================

def main():
    st.set_page_config(layout="wide")
    st.title("📅 OptiTime: Student Timetable Viewer")
    st.markdown("Use this interface to view the generated weekly schedule for any student in the large dataset.")

    df_courses, df_students, df_schedule = load_data()
    
    # Get all unique student IDs for the dropdown
    student_ids = sorted(df_students['student_id'].unique().tolist())
    
    # Sidebar for selection
    st.sidebar.header("Select Student")
    selected_id = st.sidebar.selectbox(
        "Student ID",
        student_ids
    )

    if selected_id:
        student_name, student_timetable = get_student_schedule(selected_id, df_students, df_schedule, df_courses)
        
        if student_name is None:
            st.warning(f"Student ID: {selected_id} not found in the student records.")
            return

        st.header(f"Schedule for: {student_name} ({selected_id})")
        
        if student_timetable.empty:
            st.info("This student is not scheduled for any courses this week based on the current timetable.")
        else:
            # Display the timetable as an HTML table for styling
            st.markdown(student_timetable.to_html(escape=False), unsafe_allow_html=True)
            
            st.subheader("Enrolled Courses")
            
            # Show a list of all courses this student is taking
            enrolled_cids = df_students[df_students['student_id'] == selected_id]['course_id'].tolist()
            enrolled_details = df_courses[df_courses['course_id'].isin(enrolled_cids)][['course_id', 'title', 'instructor1', 'credits']]
            enrolled_details.columns = ['ID', 'Title', 'Instructor', 'Credits']
            st.dataframe(enrolled_details, hide_index=True, use_container_width=True)

if __name__ == "__main__":
    main()
